"""
water_tank.py  —  Water Tank Physics & Validation Engine
=========================================================
Layer 1  |  PhysicsGuard ICS Security Gateway
Week 1 deliverable: WaterTankController — single-source-of-truth
for all physical state, physics simulation, and validation logic.

Owns:
  - All physical state: level, valve, pump
  - Physics simulation:  update_physics()
  - Validation:          set_valve_position(), set_pump_state()
  - Violation history:   append-only deque, exposed via property

Does NOT own:
  - Modbus register handling (modbus_server.py)
  - Thread creation / network I/O
  - Rule management      (validation_engine.py — Layer 4)

Bug-fix notes (see §5 of PHYSICSGUARD_CONTEXT.md):
  B02 — time.monotonic() for dt; time.time() for violation timestamps
  B03 — pump OFF command always allowed, never checked against interlock
  B04 — blocked command restores ACTUAL current value, never hardcoded 0
  B07 — _violations is private; .violations property returns a copy
  B08 — lock released before any I/O or external call
  B11 — physics force-close updates _last_valve_cmd_time (rate-timer reset)
  B12 — __post_init__ validates all constants; ZeroDivisionError impossible
  B13 — violation timestamps use time.time(), not time.monotonic()
  B14 — no dead try/except around constants; __post_init__ catches all

Design-fix notes:
  D01 — @dataclass(eq=False): autogenerated __eq__ compares only constants;
        runtime state lives in __post_init__, so two tanks with different levels
        would falsely appear equal without this.
  D02 — set_pump_state accepts now= for deterministic testing, consistent with
        set_valve_position. Reserved for future cooldown rules.
  D03 — Rate check treats dt==0 as infinite rate (instant change → blocked),
        preventing silent bypass when two commands share a monotonic tick.
  D04 — _last_valve_cmd_time NOT updated on R001 blocks. Rate window runs from
        last accepted command; out-of-range flood cannot reset the timer.
  D05 — VIOLATION_HISTORY_MAXLEN is a named class constant; override for sims.
  D17 — _seed_state() is the single approved test back-door for seeding state.
"""

import logging
import threading
import time
from collections import deque
from dataclasses import dataclass, field
from typing import Any

__all__ = ["WaterTankController"]

log = logging.getLogger(__name__)


# ── Module-level helpers ──────────────────────────────────────────────────────

def _ok(reason: str = "ACCEPTED", **extra: Any) -> dict[str, Any]:
    """Return a dict representing an allowed command."""
    return {"allowed": True, "reason": reason, **extra}


def _block(reason: str, **extra: Any) -> dict[str, Any]:
    """Return a dict representing a blocked command."""
    return {"allowed": False, "reason": reason, **extra}


# ── Controller ────────────────────────────────────────────────────────────────

@dataclass(eq=False)   # D01: autogenerated __eq__ compares only constants;
                       # runtime state lives in __post_init__, not fields.
class WaterTankController:
    """
    Physics model and inline validation engine for a single water tank.

    Register map (mirrors modbus_server.py HR addresses, 0-based):
      HR[0] — tank_level      READ-ONLY, 0–100 %  (physics loop only)
      HR[1] — valve_position  READ-WRITE, 0–100 % (rate ≤ MAX_VALVE_RATE)
      HR[2] — pump_state      READ-WRITE, 0=OFF 1=ON (dry-run interlock)

    Thread safety:
      ALL public methods acquire self._lock.
      update_physics() is the ONLY path allowed to write tank_level.
      set_valve_position() and set_pump_state() are the ONLY paths that
      change valve/pump state — they never call update_physics() internally.

    Usage::

        tank = WaterTankController()
        # In physics thread:
        state = tank.update_physics()
        # In Modbus request thread:
        result = tank.set_valve_position(50.0)
        if not result["allowed"]:
            print(result["reason"])
    """

    # ── Physical constants (named, with units) ────────────────────────────────
    TANK_CAPACITY_LITERS: float = 1_000.0   # L        — total volume
    MAX_FLOW_RATE_LPS:    float =    10.0   # L/s      — fill rate at valve=100%
    DRAIN_RATE_LPS:       float =     3.0   # L/s      — pump drain rate (fixed)
    OVERFLOW_LEVEL:       float =    95.0   # %        — emergency force-close
    DRY_RUN_LEVEL:        float =    10.0   # %        — minimum to START pump
    MAX_VALVE_RATE:       float =     5.0   # %/s      — maximum valve slew rate
    MAX_PHYSICS_STEP:     float =     1.0   # s        — clamp dt (sim stability)
    INITIAL_LEVEL:        float =    50.0   # %        — startup state           # FIX: removed 3 extra leading spaces
    # D05: named constant — increase for long-running attack simulations
    VIOLATION_HISTORY_MAXLEN: int   =   1_000   # records  — rolling window

    def __post_init__(self) -> None:
        # Validate constants — catches misconfiguration at construction time (B12, B14)
        if self.TANK_CAPACITY_LITERS <= 0:
            raise ValueError(
                f"TANK_CAPACITY_LITERS must be > 0, got {self.TANK_CAPACITY_LITERS}"
            )
        if self.MAX_FLOW_RATE_LPS <= 0:
            raise ValueError(
                f"MAX_FLOW_RATE_LPS must be > 0, got {self.MAX_FLOW_RATE_LPS}"
            )
        if self.DRAIN_RATE_LPS < 0:
            raise ValueError(
                f"DRAIN_RATE_LPS must be >= 0, got {self.DRAIN_RATE_LPS}"
            )
        if not (0.0 < self.OVERFLOW_LEVEL <= 100.0):
            raise ValueError(
                f"OVERFLOW_LEVEL must be in (0, 100], got {self.OVERFLOW_LEVEL}"
            )
        if not (0.0 <= self.DRY_RUN_LEVEL < self.OVERFLOW_LEVEL):
            raise ValueError(
                f"DRY_RUN_LEVEL must be in [0, OVERFLOW_LEVEL), "
                f"got {self.DRY_RUN_LEVEL}"
            )
        if self.MAX_VALVE_RATE <= 0:
            raise ValueError(
                f"MAX_VALVE_RATE must be > 0, got {self.MAX_VALVE_RATE}"
            )
        if not (0.0 <= self.INITIAL_LEVEL <= 100.0):
            raise ValueError(
                f"INITIAL_LEVEL must be in [0, 100], got {self.INITIAL_LEVEL}"
            )
        if self.VIOLATION_HISTORY_MAXLEN <= 0:
            raise ValueError(
                f"VIOLATION_HISTORY_MAXLEN must be > 0, got {self.VIOLATION_HISTORY_MAXLEN}"
            )

        # ── Mutable state — ALL protected by _lock ────────────────────────────
        self._lock:               threading.Lock = threading.Lock()
        self._tank_level:         float          = self.INITIAL_LEVEL
        self._inlet_valve:        float          = 0.0    # % closed
        self._pump_running:       bool           = False
        self._last_physics_time:  float          = time.monotonic()
        # _last_valve_cmd_time:
        #   0.0 on startup means "no prior command" — rate check skipped
        #   for the very first command (attacker can't exploit this because
        #   first command is still range-checked, and rate check activates
        #   from the second command onward)
        self._last_valve_cmd_time: float = 0.0   # monotonic

        # D05: maxlen driven by named constant so subclasses/tests can override
        self._violations: deque = deque(maxlen=self.VIOLATION_HISTORY_MAXLEN)

    # ── Public properties ─────────────────────────────────────────────────────

    @property
    def violations(self) -> list[dict]:
        """Thread-safe snapshot copy of the violation log (B07)."""
        with self._lock:
            return list(self._violations)

    # ── State snapshot ────────────────────────────────────────────────────────

    def get_state(self) -> dict[str, Any]:
        """
        Return a complete thread-safe snapshot of all physical state.
        Safe to call from any thread at any time.
        """
        with self._lock:
            return self._snapshot()

    def _snapshot(self) -> dict[str, Any]:
        """
        Build state dict.
        MUST be called from within self._lock.
        """
        return {
            # Float values (for physics / validation logic)
            "tank_level":     self._tank_level,
            "valve_position": self._inlet_valve,
            "pump_running":   self._pump_running,
            # Rate-rule support: ValidationEngine R002 reads this to compute dt
            "last_cmd_time":  self._last_valve_cmd_time,
            # Integer values (for Modbus register writes — 1 % resolution)
            "tank_level_int": round(self._tank_level),
            "valve_int":      round(self._inlet_valve),
            "pump_int":       int(self._pump_running),
        }

    # ── Physics loop ──────────────────────────────────────────────────────────

    def update_physics(self, now: float | None = None) -> dict[str, Any]:
        """
        Advance the physics simulation by dt seconds.
        MUST be called by the physics loop thread only.

        Args:
            now: override for testing — pass time.monotonic() value.
                 If None, uses time.monotonic() internally.

        Returns:
            Updated state snapshot.

        Physics model:
            net_flow = (valve/100) × MAX_FLOW_RATE − pump × DRAIN_RATE   [L/s]
            level_change = (net_flow × dt / TANK_CAPACITY) × 100          [%]

        Safety interlocks (physics enforces regardless of validation):
            Overflow  (level ≥ OVERFLOW_LEVEL): force-close valve
            Drain-out (level ≤ 0 with pump on): stop pump
        """
        if now is None:
            now = time.monotonic()

        with self._lock:
            dt = now - self._last_physics_time
            # Clamp dt to prevent simulation explosion on slow ticks (B12 guard)
            dt = max(0.0, min(dt, self.MAX_PHYSICS_STEP))
            self._last_physics_time = now

            if dt <= 0.0:
                return self._snapshot()

            # Net flow rate (L/s)
            fill_lps  = (self._inlet_valve / 100.0) * self.MAX_FLOW_RATE_LPS
            drain_lps = self.DRAIN_RATE_LPS if self._pump_running else 0.0
            net_lps   = fill_lps - drain_lps

            # Level change (%) — no division by zero possible (validated in __post_init__)
            level_delta_pct = (net_lps * dt / self.TANK_CAPACITY_LITERS) * 100.0
            new_level = self._tank_level + level_delta_pct
            self._tank_level = max(0.0, min(100.0, new_level))

            # ── Overflow interlock: force-close valve ─────────────────────────
            # B11 FIX: ALWAYS update _last_valve_cmd_time when valve changes
            # by ANY code path, including physics safety overrides.
            # Without this, the rate-limit timer is stale after a force-close,
            # and an attacker can bypass R002 immediately after overflow.
            if self._tank_level >= self.OVERFLOW_LEVEL and self._inlet_valve > 0.0:
                log.warning(
                    "PHYSICS SAFETY | OVERFLOW | level=%.1f%% → force-close valve",
                    self._tank_level,
                )
                self._inlet_valve = 0.0
                self._last_valve_cmd_time = now   # ← B11 fix

            # ── Drain-out interlock: stop pump when tank is empty ─────────────
            if self._pump_running and self._tank_level <= 0.0:
                log.warning("PHYSICS SAFETY | DRAIN-OUT | tank empty → stopping pump")
                self._pump_running = False

            return self._snapshot()

    # ── Commanded writes ──────────────────────────────────────────────────────

    def set_valve_position(
        self,
        target: float,
        now:    float | None = None,
    ) -> dict[str, Any]:
        """
        Attempt to set the inlet valve to target %.

        Validation chain:
            R001 (CRITICAL, T0855) — target must be in [0, 100]
            R002 (CRITICAL, T0855) — |Δ| / dt must be ≤ MAX_VALVE_RATE %/s

        Args:
            target: proposed valve position [%]
            now:    time.monotonic() override for testing

        Returns:
            _ok(...)   if command is accepted
            _block(...) if command is blocked — actual valve unchanged
        """
        if now is None:
            now = time.monotonic()

        with self._lock:
            # ── R001: Range check ─────────────────────────────────────────────
            if not (0.0 <= target <= 100.0):
                reason = (
                    f"R001 RANGE | valve {target:.2f}% outside [0, 100] | "
                    f"MITRE T0855"
                )
                self._record_violation(
                    register=1, value=target, reason=reason,
                    rule_id="R001", severity="CRITICAL", mitre_tag="T0855",
                )
                return _block(reason, rule_id="R001", current=self._inlet_valve)

            # ── R002: Rate-of-change check ────────────────────────────────────
            if self._last_valve_cmd_time > 0.0:
                # B02 fix: time.monotonic() only — immune to NTP jumps
                dt = now - self._last_valve_cmd_time
                # D03 fix: dt==0 means same monotonic tick — treat as infinite
                # rate so the check is never silently bypassed.
                if dt <= 0.0:
                    rate = float("inf")
                else:
                    rate = abs(target - self._inlet_valve) / dt
                if rate > self.MAX_VALVE_RATE:
                    reason = (
                        f"R002 RATE | {rate:.2f} %/s exceeds limit "
                        f"{self.MAX_VALVE_RATE} %/s | "
                        f"Δvalve={target - self._inlet_valve:+.2f}% in "
                        f"{dt:.3f} s | MITRE T0855"
                    )
                    self._record_violation(
                        register=1, value=target, reason=reason,
                        rule_id="R002", severity="CRITICAL", mitre_tag="T0855",
                    )
                    return _block(reason, rule_id="R002", current=self._inlet_valve)

            # ── Accepted ──────────────────────────────────────────────────────
            self._inlet_valve = target
            self._last_valve_cmd_time = now
            return _ok(f"valve set to {target:.1f}%")

    def set_pump_state(
        self,
        running: bool,
        now:     float | None = None,   # D02: injected clock for future cooldown rules
    ) -> dict[str, Any]:
        """
        Attempt to start or stop the pump.

        Validation chain:
            Turning OFF: ALWAYS allowed — never checked (B03 fix)
            Turning ON:  R003 (EMERGENCY, T0813) — tank_level must be ≥ DRY_RUN_LEVEL

        Args:
            running: True = start pump, False = stop pump

        Returns:
            _ok(...)    if command is accepted
            _block(...) if command is blocked — pump state unchanged
        """
        if now is None:
            now = time.monotonic()   # D02: resolved here, ready for future rules

        with self._lock:
            # ── Pump OFF: unconditionally allowed (B03 fix) ───────────────────
            if not running:
                self._pump_running = False
                return _ok("pump stopped")

            # ── Pump ON: dry-run interlock check ─────────────────────────────
            if self._tank_level < self.DRY_RUN_LEVEL:
                reason = (
                    f"R003 INTERLOCK | pump start blocked — "
                    f"level {self._tank_level:.1f}% < "
                    f"minimum {self.DRY_RUN_LEVEL}% | MITRE T0813"
                )
                self._record_violation(
                    register=2, value=1.0, reason=reason,
                    rule_id="R003", severity="EMERGENCY", mitre_tag="T0813",
                )
                return _block(reason, rule_id="R003", current=int(self._pump_running))

            # ── Accepted ──────────────────────────────────────────────────────
            self._pump_running = True
            return _ok("pump started")

    # ── Test helpers ─────────────────────────────────────────────────────────

    def _seed_state(
        self,
        tank_level:   float | None = None,
        valve:        float | None = None,
        pump_running: bool  | None = None,
    ) -> None:
        """
        TEST-ONLY back-door for seeding mutable state without going through
        the public validation API.

        D17: approved way for tests to set up pre-conditions (e.g. pump already
        running) without mutating private fields directly.  Direct mutation
        bypasses the lock and couples tests to internal field names.
        Only fields explicitly passed (not None) are updated.

        NOT for production use — bypasses all validation and interlocks.
        """
        with self._lock:
            if tank_level is not None:
                self._tank_level = max(0.0, min(100.0, float(tank_level)))
            if valve is not None:
                self._inlet_valve = max(0.0, min(100.0, float(valve)))
            if pump_running is not None:
                self._pump_running = bool(pump_running)

    # ── Internal helpers ──────────────────────────────────────────────────────

    def _record_violation(
        self,
        register:  int,
        value:     float,
        reason:    str,
        rule_id:   str,
        severity:  str,
        mitre_tag: str,
    ) -> None:
        """
        Append a violation record and emit a WARNING log.
        MUST be called from within self._lock.

        B13 fix: timestamp uses time.time() (wall clock) for human-readable
        logs and database storage.
        """
        record: dict[str, Any] = {
            "timestamp": time.time(),   # B13: wall-clock, NOT monotonic
            "register":  register,
            "value":     value,
            "reason":    reason,
            "rule_id":   rule_id,
            "severity":  severity,
            "mitre_tag": mitre_tag,
        }
        self._violations.append(record)
        # B08: log AFTER writing to deque, before releasing lock —
        # logging.warning() is thread-safe and non-blocking; acceptable here
        log.warning(
            "BLOCKED [%s] reg=%d val=%.2f — %s",
            rule_id, register, value, reason,
        )
